# Bioinformatics Project - Computational Drug Discovery [Part 3-4] Descriptor Calculation, Dataset Preparation And Regression Model (Random Forest)
Chanin Nantasenamat

'Data Professor' YouTube channel: http://youtube.com/dataprofessor

In this Jupyter notebook, we will be building a real-life data science project that you can include in your data science portfolio. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In Part 3, we will be calculating molecular descriptors that are essentially quantitative description of the compounds in the dataset. Finally, we will be preparing this into a dataset for subsequent model building in Part 4.

# **PaDELPy**

The original script uses the Padel software to calculate molecular descriptors through the jave/bash version. Here, will be used the PadelPy, which is the python version of the software

## Install PaDELPy

In [2]:
! pip install padelpy

Requirement already satisfied: padelpy in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (0.1.17)

## Downloading fingerprint .xml files

In [4]:
! wget https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip

### **Unzip your fingerprints xml and upload the files**

## List and sort fingerprint XML files

In [3]:
import glob
xml_files = glob.glob("*.xml")
xml_files.sort()
xml_files

['AtomPairs2DFingerprintCount.xml',
 'AtomPairs2DFingerprinter.xml',
 'EStateFingerprinter.xml',
 'ExtendedFingerprinter.xml',
 'Fingerprinter.xml',
 'GraphOnlyFingerprinter.xml',
 'KlekotaRothFingerprintCount.xml',
 'KlekotaRothFingerprinter.xml',
 'MACCSFingerprinter.xml',
 'PubchemFingerprinter.xml',
 'SubstructureFingerprintCount.xml',
 'SubstructureFingerprinter.xml']

In [4]:
# List of fingerprints
FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'CDKextended',
 'CDK',
 'CDKgraphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

## Create a dictionary

In [5]:
fp = dict(zip(FP_list, xml_files))
fp

{'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml',
 'Substructure': 'SubstructureFingerprinter.xml'}

In [6]:
fp['AtomPairs2D']

'AtomPairs2DFingerprinter.xml'

## **Load bioactivity data**
Download the curated ChEMBL bioactivity data that has been pre-processed from Parts 1 and 2 of this Bioinformatics Project series. Here we will be using the **bioactivity_data_3class_pIC50.csv** file that essentially contain the pIC50 values that we will be using for building a regression model.

In [7]:
import pandas as pd

In [8]:
df3 = pd.read_csv('acetylcholinesterase_04_bioactivity_data_3class_pIC50.csv')

In [9]:
df3

,Unnamed: 0,molecule_chembl_id,canonical_smiles,class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,active,312.325,2.80320,0.0,5.0,6.124939
1,1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,active,376.913,4.55460,0.0,4.0,7.000000
2,2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,inactive,426.851,5.35740,0.0,4.0,4.301030
3,3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,active,404.845,4.70690,0.0,4.0,6.522879
4,4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,active,346.334,3.09530,0.0,5.0,6.096910
...,...,...,...,...,...,...,...,...,...
7170,7170,CHEMBL6190210,FC(F)(F)c1cccc(-c2cc(-c3cccs3)n(-c3ccc(Br)cc3)...,active,449.295,7.04910,0.0,2.0,9.318759
7171,7171,CHEMBL6192902,O=C(NNC(=S)Nc1ccccc1[N+](=O)[O-])c1sccc1Cl,active,356.816,2.94110,3.0,5.0,6.397940
7172,7172,CHEMBL6191782,Cc1cc(=O)[nH]c2c1C(=O)C(NCNc1c3c(nc4ccccc14)CC...,active,414.465,3.03242,3.0,6.0,7.954677
7173,7173,CHEMBL6190113,O=C(NCCCNc1c2c(nc3ccccc13)CCC2)c1cnc(Cl)c(Cl)c1,active,415.324,4.65730,2.0,4.0,7.283997
7174,7174,CHEMBL6188323,COc1cc2c(cc1OC)CC(CN1CCN(CCCNc3c4c(nc5cc(Cl)cc...,active,601.235,6.73600,1.0,6.0,8.583359

## Prepare data subset as input to padel

In [10]:
selection = ['canonical_smiles', 'molecule_chembl_id']
df3_selection  = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [11]:
df3_selection

                                       canonical_smiles molecule_chembl_id
0                 CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1       CHEMBL133897
1            O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1       CHEMBL336398
2     CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1       CHEMBL131588
3         O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F       CHEMBL130628
4             CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C       CHEMBL130478
...                                                 ...                ...
7170  FC(F)(F)c1cccc(-c2cc(-c3cccs3)n(-c3ccc(Br)cc3)...      CHEMBL6190210
7171         O=C(NNC(=S)Nc1ccccc1[N+](=O)[O-])c1sccc1Cl      CHEMBL6192902
7172  Cc1cc(=O)[nH]c2c1C(=O)C(NCNc1c3c(nc4ccccc14)CC...      CHEMBL6191782
7173    O=C(NCCCNc1c2c(nc3ccccc13)CCC2)c1cnc(Cl)c(Cl)c1      CHEMBL6190113
7174  COc1cc2c(cc1OC)CC(CN1CCN(CCCNc3c4c(nc5cc(Cl)cc...      CHEMBL6188323

[7175 rows x 2 columns]

## Calculate Descriptors

There are 12 fingerprint types in PaDEL. To calculate all 12, make sure to make adjustments to the descriptortypes input argument to any of the ones in the fp dictionary variable as shown above, e.g. SubstructureFingerprintCount.xml

In [12]:
fp

{'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml',
 'Substructure': 'SubstructureFingerprinter.xml'}

In [13]:
fp['PubChem']

'PubchemFingerprinter.xml'

In [14]:
from padelpy import padeldescriptor

fingerprint = 'PubChem'

fingerprint_output_file = ''.join([fingerprint, '.csv']) #substructure .csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='molecule.smi',
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='substructureFingerprint.xml',
                descriptortypes=fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,fingerprints=True)

## Display Calculated Fingerprints

In [15]:
descriptors = pd.read_csv(fingerprint_output_file)
descriptors

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL133897,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL336398,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL131588,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL130628,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL130478,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7170,CHEMBL6190210,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7171,CHEMBL6192902,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7172,CHEMBL6191782,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7173,CHEMBL6190113,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7174,CHEMBL6188323,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Build a Random Forest Model

In [21]:
X = descriptors.drop('Name', axis=1)
y = df3['pIC50']

## Remove low variance features

In [25]:
! pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in /home/bruno/miniforge3/envs/jupyter_env/lib/python3.14/site-packages (from scikit-learn) (1.18.0)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.9.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 9.7 MB/s  0:00:00m eta 0:00:01
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Installing collected packages: threadpoolctl, narwhals, cloudpickle, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [scikit-learn][0m [scikit-learn]
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.26.0 scikit-learn-1.9.1 threadpoolctl-3.7.0

In [17]:
from sklearn.feature_selection import VarianceThreshold

def remove_low_variance(input_data, threshold=0.1):
    selection = VarianceThreshold(threshold)
    selection.fit(input_data)
    return input_data[input_data.columns[selection.get_support(indices=True)]]

X = remove_low_variance(X, threshold=0.1)
X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP12,PubchemFP13,PubchemFP15,PubchemFP16,PubchemFP19,PubchemFP20,...,PubchemFP761,PubchemFP776,PubchemFP777,PubchemFP779,PubchemFP797,PubchemFP798,PubchemFP818,PubchemFP819,PubchemFP821,PubchemFP824
0,1,1,1,0,1,0,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,0,0,0,1,1,1,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7170,1,1,0,0,1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7171,1,1,0,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
7172,1,1,1,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,1,0
7173,1,1,1,0,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,1,0
7174,1,1,1,1,1,1,1,1,1,0,...,1,1,1,0,1,1,1,0,1,1

## Data Splitting

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
X_train.shape, X_test.shape

((5740, 219), (1435, 219))

## Model Building

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import matthews_corrcoef

model = RandomForestClassifier(n_estimators=500, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=500, random_state=42)

In [32]:
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

RandomForestClassifier(max_features='auto', n_estimators=500, random_state=42)

## Apply the Model to make the prediction

In [33]:
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

## Scatter Plot of Experimental vs Predicted pIC50 Values

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.set(color_codes=True)
sns.set_style("white")

ax = sns.regplot(Y_test, Y_pred, scatter_kws={'alpha':0.4})
ax.set_xlabel('Experimental pIC50', fontsize='large', fontweight='bold')
ax.set_ylabel('Predicted pIC50', fontsize='large', fontweight='bold')
ax.set_xlim(0, 12)
ax.set_ylim(0, 12)
ax.figure.set_size_inches(5, 5)
plt.show

## Calculate model performance metrics

In [34]:
mcc_train = matthews_corrcoef(y_train, y_train_pred)
mcc_train

0.9361035703242894

In [36]:
mcc_test = matthews_corrcoef(y_test, y_test_pred)
mcc_test

0.5965476471750033

## Cross-validation

In [37]:
from sklearn.model_selection import cross_val_score

rf = RandomForestClassifier(n_estimators=500, random_state=42)
cv_scores = cross_val_score(rf, X_train, y_train, cv=5)
cv_scores

array([0.72648084, 0.7325784 , 0.73344948, 0.7325784 , 0.7195122 ])

In [38]:
mcc_cv = cv_scores.mean()
mcc_cv

np.float64(0.7289198606271776)

In [39]:
model_name = pd.Series(['Random forest'], name='Name')
mcc_train_series = pd.Series(mcc_train, name='MCC_train')
mcc_cv_series = pd.Series(mcc_cv, name='MCC_cv')
mcc_test_series = pd.Series(mcc_test, name='MCC_test')

performance_metrics = pd.concat([model_name, mcc_train_series, mcc_cv_series, mcc_test_series], axis=1)
performance_metrics

            Name  MCC_train   MCC_cv  MCC_test
0  Random forest   0.936104  0.72892  0.596548

## download the CSV File

In [40]:
descriptors.to_csv('acetylcholinesterase_06_bioactivity_data_3class_pIC50_pubchem_fp.csv', index=False)